language: generic

matrix:
  include:
    - name: 'Conda Python with Specfile'
      install:
        - sudo apt-get update && sudo apt-get install -y wget
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - source "$HOME/miniconda/etc/profile.d/conda.sh"
        - hash -r
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        - conda create --name simple_network_sim --file spec-file.txt
        - conda activate simple_network_sim
      script:
        - pytest --cov=simple_network_sim
      after_success:
        - coverage xml
        - bash <(curl -s https://codecov.io/bash)
